'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' ChangePassword control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.DevExpress.Web.ASPxHyperLink

    ''' <summary>
    ''' CreatePassword control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.DevExpress.Web.ASPxHyperLink

    ''' <summary>
    ''' PhoneNumber control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' PhoneNumber control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents RemovePhone As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' TwoFactorDisable control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents TwoFactorDisable As Global.DevExpress.Web.ASPxButton
        
    ''' <summary>
    ''' TwoFactorEnable control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected WithEvents TwoFactorEnable As Global.DevExpress.Web.ASPxButton
    
End Class