'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Public Partial Class VerifyPhoneNumber
    ''' <summary>
    ''' ErrorMessage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ErrorMessage As Global.System.Web.UI.WebControls.Literal

    ''' <summary>
    ''' PhoneNumber control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Code As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' HiddenField control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HiddenField As Global.DevExpress.Web.ASPxHiddenField

    ''' <summary>
    ''' btnSubmit control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnSubmit As Global.DevExpress.Web.ASPxButton
End Class