'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TimeClock

    '''<summary>
    '''DdlEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlEmployees As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblStandardClockInLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStandardClockInLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblStandardClockIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStandardClockIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblStandardClockOutLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStandardClockOutLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblStandardClockOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStandardClockOut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelTimePunches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTimePunches As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LblInTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblInTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblOutTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblOutTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnClockIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClockIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnClockOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClockOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnClockInEarly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClockInEarly As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnClockOutLate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClockOutLate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatePicker As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''LblStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridTimePunches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridTimePunches As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''SdsHourlyEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SdsHourlyEmployees As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SdsTimePunches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SdsTimePunches As Global.System.Web.UI.WebControls.SqlDataSource
End Class
